[package]
name = "quaddrop"
version = "0.1.0"
authors = ["Drew Stone <drewstone329@gmail.com>"]
edition = "2018"

[dependencies]
hex-literal = "0.2.1"
hex = "0.3.2"
serde_json = "1.0"
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
hedgeware-parachain-primitives = { path = "../primitives", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

[features]
default = [ "std" ]
std = [
	"serde",
	"codec/std",
	"hedgeware-parachain-primitives/std",
]
