[package]
name = "hedgeware-rpc-trace"
version = '0.6.0'
authors = ['PureStake']
edition = '2018'
homepage = 'https://edgewa.re'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
# Utils
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.8"
ethereum-types = "0.11.0"
ethereum = { version = "0.7.1", features = ["with-codec"] }

# Async and logs
tokio = { version = "0.2.13", features = ["sync", "time"] }
futures = { version = "0.3", features = ["compat"] }
tracing = "0.1.25"

# Primitives
sp-runtime = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-utils = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-api = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-io = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-std = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-blockchain = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-transaction-pool = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-block-builder = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
fp-rpc = { git = "https://github.com/webb-tools/frontier", branch = "polkadot-v0.9.7" }
hedgeware-rpc-primitives-debug = { path = "../../../rpc-primitives/debug" }

# Client and RPC
jsonrpc-core = "15.0.0"
sc-client-api = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-network = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-transaction-graph = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
fc-rpc = { git = "https://github.com/webb-tools/frontier", branch = "polkadot-v0.9.7" }
fc-consensus = { git = "https://github.com/webb-tools/frontier", branch = "polkadot-v0.9.7" }
fc-rpc-core = { git = "https://github.com/webb-tools/frontier", branch = "polkadot-v0.9.7" }
hedgeware-rpc-core-trace = { path = "../../rpc-core/trace" }
